# To use this file, run `docker-compose up`.
version: '3'

services:

  # Main application
  app:
    build: ./devops/docker/tasking-manager
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  # Migration service
  migration:
    build: ./devops/docker/tasking-manager
    volumes:
      - .:/usr/src/app

  # postgres
  postgresql:
    environment: 
      - POSTGRES_PASSWORD=tm
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment: 
      - ADMINER_PLUGINS=tables-filter
    ports:
      - 8080:8080